### ISSUE TITLE
Use Spring Boot 2.3's GA Version

### ISSUE THREAD

**Issue by cho0o0** [gofabian/spring-boot-data-r2dbc-jooq#24]
Current project depends on Spring Boot 2.3.0.M4, which makes it necessary to add `https://repo.spring.io/milestone` as a repository. Spring Boot 2.3 already went GA, thus it will be more convenience to use if the project's dependency is updated.

**Comment by gofabian** [comment]
Yes, you are totally right. I updated all dependencies to the latest versions.
